# Generated by Django 4.1.2 on 2023-04-21 01:55

import ToolOwnershipTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('assigned', models.CharField(max_length=50, null=True, verbose_name=ToolOwnershipTracker.models.User)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('toolType', models.CharField(choices=[('H', 'Handtool'), ('P', 'Powertool'), ('D', 'Operatable'), ('O', 'Other')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Toolbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jobsite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.jobsite')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('S', 'Supervisor'), ('A', 'Admin'), ('U', 'User')], default='U', max_length=1)),
                ('password', models.CharField(max_length=32)),
                ('address', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=14)),
                ('forget_password_token', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ToolReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('created', models.DateField()),
                ('time', models.TimeField()),
                ('reportType', models.CharField(choices=[('R', 'Report'), ('D', 'Damaged'), ('I', 'Injury'), ('L', 'Lost')], default='R', max_length=1)),
                ('description', models.CharField(max_length=350)),
                ('jobsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.jobsite')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user')),
                ('tool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.tool')),
                ('toolbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.toolbox')),
            ],
        ),
        migrations.AddField(
            model_name='toolbox',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user'),
        ),
        migrations.AddField(
            model_name='tool',
            name='toolbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.toolbox'),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user'),
        ),
    ]
