# Generated by Django 4.1.2 on 2023-04-12 18:07

import ToolOwnershipTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsite',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('assigned', models.CharField(max_length=50, null=True, verbose_name=ToolOwnershipTracker.models.User)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('S', 'Supervisor'), ('A', 'Admin'), ('U', 'User')], default='U', max_length=1)),
                ('password', models.CharField(max_length=32)),
                ('address', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=14)),
                ('forget_password_token', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Toolbox',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('tools', models.CharField(max_length=50, null=True, verbose_name=ToolOwnershipTracker.models.User)),
                ('jobsite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.jobsite')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('toolbox', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.toolbox')),
            ],
        ),
        migrations.AddField(
            model_name='jobsite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user'),
        ),
    ]
