# Generated by Django 4.1.2 on 2023-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsite',
            name='assigned',
        ),
        migrations.AddField(
            model_name='jobsite',
            name='assigned',
            field=models.ManyToManyField(related_name='users', to='ToolOwnershipTracker.user'),
        ),
    ]
