# Generated by Django 4.1.2 on 2023-04-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
