# Generated by Django 4.1.2 on 2023-04-29 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0002_alter_jobsite_id_alter_tool_id_alter_toolbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolreport',
            name='jobsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.jobsite'),
        ),
    ]
