# Generated by Django 4.1.2 on 2023-04-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0002_remove_jobsite_assigned_jobsite_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='assigned',
            field=models.ManyToManyField(max_length=50, related_name='user', to='ToolOwnershipTracker.user'),
        ),
    ]
