# Generated by Django 4.1.2 on 2023-04-14 01:43

import ToolOwnershipTracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0003_alter_jobsite_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='toolbox',
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='tools',
            field=models.CharField(max_length=50, null=True, verbose_name=ToolOwnershipTracker.models.Tool),
        ),
    ]
