# Generated by Django 4.1.2 on 2023-04-14 02:05

import ToolOwnershipTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0004_remove_tool_toolbox_alter_toolbox_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsite',
            name='assigned',
        ),
        migrations.CreateModel(
            name='ToolReport',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('reporter', models.CharField(max_length=50, verbose_name=ToolOwnershipTracker.models.User)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tool', models.CharField(max_length=50, null=True, verbose_name=ToolOwnershipTracker.models.Tool)),
                ('jobSite', models.CharField(max_length=50, verbose_name=ToolOwnershipTracker.models.Jobsite)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reportType', models.CharField(choices=[('R', 'Report'), ('D', 'Damaged'), ('I', 'Injury'), ('L', 'Lost')], default='R', max_length=1)),
                ('description', models.CharField(max_length=350)),
                ('impactedUsers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user')),
            ],
        ),
        migrations.AddField(
            model_name='jobsite',
            name='assigned',
            field=models.CharField(max_length=50, null=True, verbose_name=ToolOwnershipTracker.models.User),
        ),
    ]
