# Generated by Django 4.1.2 on 2023-04-14 02:08

import ToolOwnershipTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0005_remove_jobsite_assigned_toolreport_jobsite_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolreport',
            name='impactedUsers',
        ),
        migrations.AddField(
            model_name='tool',
            name='toolType',
            field=models.CharField(max_length=1, null=True, verbose_name=ToolOwnershipTracker.models.ToolType),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='jobSite',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.jobsite'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='reporter',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='tool',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.tool'),
        ),
    ]
