# Generated by Django 4.1.2 on 2023-04-14 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0006_remove_toolreport_impactedusers_tool_tooltype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolbox',
            name='tools',
        ),
        migrations.AddField(
            model_name='tool',
            name='toolbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.toolbox'),
        ),
    ]
