# Generated by Django 4.1.2 on 2023-04-14 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0007_remove_toolbox_tools_tool_toolbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolreport',
            name='toolbox',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.toolbox'),
        ),
    ]
