# Generated by Django 4.1.2 on 2023-04-14 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0008_toolreport_toolbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolreport',
            old_name='jobSite',
            new_name='jobsite',
        ),
    ]
