# Generated by Django 4.1.2 on 2023-04-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0009_rename_jobsite_toolreport_jobsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolreport',
            old_name='jobsite',
            new_name='jobSite',
        ),
    ]
