# Generated by Django 4.1.2 on 2023-04-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0010_rename_jobsite_toolreport_jobsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolreport',
            name='jobSite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.jobsite'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.user'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.tool'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='toolbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ToolOwnershipTracker.toolbox'),
        ),
    ]
