# Generated by Django 4.1.2 on 2023-04-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0011_alter_toolreport_jobsite_alter_toolreport_reporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='toolType',
        ),
        migrations.RemoveField(
            model_name='toolreport',
            name='created',
        ),
        migrations.RemoveField(
            model_name='toolreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='toolreport',
            name='time',
        ),
    ]
