# Generated by Django 4.1.2 on 2023-04-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0012_remove_tool_tooltype_remove_toolreport_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolreport',
            old_name='jobSite',
            new_name='jobsite',
        ),
    ]
