# Generated by Django 4.1.2 on 2023-04-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToolOwnershipTracker', '0013_rename_jobsite_toolreport_jobsite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsite',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='jobsite',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='jobsite',
            name='title',
        ),
        migrations.RemoveField(
            model_name='toolbox',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='toolreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='toolreport',
            name='reportType',
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tool',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolbox',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='jobsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToolOwnershipTracker.jobsite'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToolOwnershipTracker.tool'),
        ),
        migrations.AlterField(
            model_name='toolreport',
            name='toolbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ToolOwnershipTracker.toolbox'),
        ),
    ]
